lib/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<str:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<str:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('genre/<str:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
]

# Borrowed books
urlpatterns += [
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'^givenbooks/$', views.GivenBooksByStaffListView.as_view(), name='my-given')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('lib.urls'))
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Add start page
urlpatterns += [
    path('', RedirectView.as_view(url='/lib/', permanent=True))
]

lib/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid


# Create your models here.


class Author(models.Model):
    """Model representing an author"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this author across whole library")
    name = models.CharField(max_length=100)
    birthday = models.DateField(null=True, blank=True)
    info = models.TextField(
        help_text="Brief information for this author", blank=True)

    def get_absolute_url(self):
        """Returns the url to access a particular author instance"""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object"""
        return self.name

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Genre(models.Model):
    """Model representing genre"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this genre")
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Book(models.Model):
    """Model representing a book"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this book across whole library")
    title = models.CharField(max_length=100)
    description = models.TextField(
        help_text="Brief description of the book", blank=True)
    author = models.ForeignKey(
        'Author', on_delete=models.SET_NULL, null=True)
    publish_year = models.DateField(null=True, blank=True)
    genre = models.ForeignKey(
        'Genre', on_delete=models.SET_NULL, null=True, default='2947d6ee-b0bf-439e-b869-e8bff3415576')

    class Meta:
        ordering = ['title', 'description']
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance"""
        return reverse('book-detail', args=[str(self.id)])
        # return reverse('book-detail', kwargs={'pk': str(self.id)})

    def __str__(self):
        """String for representing the Model object"""
        return self.title


class Order_Items(models.Model):
    """Model representing the items of an order"""
    order = models.ForeignKey(
        'Order', on_delete=models.SET_NULL, null=True)
    book = models.ManyToManyField(
        Book, help_text="Books in particular order")

    def get_books(self):
        return "\n".join([p.title for p in self.book.all()])

    def __str__(self):
        try:
            return "By 0{}:{}".format(self.order.visitor, self.get_books())
        except:
            return "None"

    class Meta:
        verbose_name = 'Книги в заказе'
        verbose_name_plural = 'Книги в заказах'


class Order(models.Model):
    """Model representing order"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for given order")
    visitor = models.ForeignKey(
        User, related_name='visitor', on_delete=models.SET_NULL, null=True, help_text="Visitor that made an order")
    staff = models.ForeignKey(
        User, related_name='staff', on_delete=models.SET_NULL, null=True, help_text="Staff that made an order")
    order_date = models.DateField(null=True)

    def __str__(self):
        return "{}: by {} on {}".format(self.id, self.visitor, self.order_date)

    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


# Comment this out due to the fact that I can create users by default
# Using django.contrib.auth.models.User
'''
class Visitor(models.Model):
    """Model representing a visitor"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for the visitor")
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=11)
    email = models.CharField(max_length=100)
    sex = models.BooleanField(null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('visitor-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Staff(models.Model):
    """Model representing staff"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for the staff person")
    name = models.CharField(max_length=100)
    sex = models.BooleanField(null=True, blank=True)
    phone_number = models.CharField(max_length=11)
    birthday = models.DateField(null=True, blank=True)
    position = models.CharField(max_length=100)
    address = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('staff-detail', args=[str(self.id)])

    def __str__(self):
        return self.name
'''

lib/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views import generic
from datetime import date, timedelta
from .models import *

paginator = 30


class BookListView(generic.ListView):
    model = Book
    paginate_by = paginator

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Book.objects.filter(title__icontains=query)
        else:
            return Book.objects.all()


class BookDetailView(generic.DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['book_list'] = Book.objects.all()
        book_id = self.request.get_full_path().split('/')[-1]
        b = Book.objects.filter(id=book_id)[0]
        try:
            user_id = Order_Items.objects.filter(book=b).values(
                'order__visitor').order_by('order__order_date')[0]['order__visitor']
            data['last_user'] = User.objects.filter(id=user_id)[0]
        except:
            data['last_user'] = 'None'

        return data


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = paginator

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Author.objects.filter(name__icontains=query)
        else:
            return Author.objects.all()


class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = Order_Items
    template_name = 'lib/book_list_borrowed_user.html'
    paginate_by = paginator

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        books = Order_Items.objects.filter(order__visitor=self.request.user).values(
            'book').order_by('order__order_date')
        data['book_list'] = Book.objects.filter(id__in=books)
        data['order_date'] = Order_Items.objects.filter(order__visitor=self.request.user).values(
            'order__order_date')[0]['order__order_date']
        data['order_date_str'] = data['order_date'].strftime('%m.%d.%Y')
        data['is_overdue'] = data['order_date'] + \
            timedelta(days=14) < date.today()
        print(data['is_overdue'])

        return data

    '''
    def get_queryset(self):
        books = Order_Items.objects.filter(order__visitor=self.request.user).values(
            'book').order_by('order__order_date')

        return Book.objects.filter(id__in=books)
    '''


class GivenBooksByStaffListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on given books by current staff user.
    """
    model = Order_Items
    template_name = 'lib/book_list_borrowed_user.html'
    paginate_by = paginator

    def get_queryset(self):
        books = Order_Items.objects.filter(order__staff=self.request.user).values(
            'book').order_by('order__order_date')

        return Book.objects.filter(id__in=books)


class GenreListView(generic.ListView):
    model = Genre
    paginate_by = 30

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Genre.objects.filter(name__icontains=query)
        else:
            return Genre.objects.all()


class GenreDetailView(generic.DetailView):
    model = Genre


def index(request):
    """View homepage"""
    num_books = Book.objects.all().count()
    num_authors = Author.objects.all().count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    return render(
        request,
        'index.html',
        context={'num_books': num_books,
                 'num_authors': num_authors,
                 'num_visits': num_visits, }
    )

lib/templates/lib/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ author }} </h1>
<p>{{author.birthday}}</p>
<p>{{author.info}}</p>
<div style="margin-left:20px;margin-top:20px">
    <h4>Книги</h4>

    <dl>
        {% for book in author.book_set.all %}
        <!-- {% url 'book-detail' book.pk %} -->
        <dt><a href="{{book.get_absolute_url}}">{{book}}</a></dt>
        <dd>{{book.description}}</dd>
        {% endfor %}
    </dl>

</div>
{% endblock %}

lib/templates/lib/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Список авторов</h1>

<form method="GET" action="" id="searchform">
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}"
        placeholder="Search..." />
</form>

{% if author_list %}
<ul>

    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">
            {{ author }}
        </a>
    </li>
    {% endfor %}

</ul>
{% else %}
<p>Нет доступных авторов.</p>
{% endif %}



{% endblock %}

lib/templates/lib/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ book.title }}</h1>

<!-- % 'author-detail' book.author.pk %}-->
<p><strong>Автор:</strong> <a href="{{book.author.get_absolute_url}}">{{ book.author }}</a></p>
<p><strong>Описание:</strong> {{ book.description }}</p>
<p><strong>Жанр:</strong> <a href="{{book.genre.get_absolute_url}}">{{ book.genre }}</a></p>
<p><strong>Последний пользователь:</strong>
    {{last_user}}
</p>
{% endblock %}

lib/templates/lib/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Список книг</h1>

<form method="GET" action="" id="searchform">
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}"
        placeholder="Search..." />
</form>

{% if book_list %}
<ul>

    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
    </li>
    {% endfor %}

</ul>
{% else %}
<p>Нет доступных книг.</p>
{% endif %}
{% endblock %}

lib/templates/lib/book_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
{% if 'lib.add_book' in user.get_all_permissions %}
<h1>Выданные книги</h1>

{% if book_list %}
<ul>

    {% for b in book_list %}
    <li><a href="{% url 'book-detail' b.id %}">{{b.title}}</a></li>

    {% endfor %}
</ul>

{% else %}
<p>Нет выданных книг.</p>
{% endif %}
{% else %}
<h1>Взятые книги</h1>

{% if book_list %}
<ul>

    {% for b in book_list %}
    <li class="{% if is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' b.id %}">{{b.title}}</a>({{order_date_str}})
    </li>

    {% endfor %}
</ul>

{% else %}
<p>Нет взятых книг.</p>
{% endif %}
{% endif %}
{% endblock %}

lib/templates/lib/genre_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ genre }} </h1>
<div style="margin-left:20px;margin-top:20px">
    <h4>Книги</h4>

    <dl>
        {% for book in genre.book_set.all %}
        <!-- {% url 'book-detail' book.pk %} -->
        <dt><a href="{{book.get_absolute_url}}">{{book}}</a></dt>
        <dd>{{book.description}}</dd>
        {% endfor %}
    </dl>

</div>
{% endblock %}

lib/templates/lib/genre_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Список жанров</h1>

<form method="GET" action="" id="searchform">
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="Поиск..." />
</form>

{% if genre_list %}
<ul>

    {% for genre in genre_list %}
    <li>
        <a href="{{ genre.get_absolute_url }}">
            {{ genre }}
        </a>
    </li>
    {% endfor %}

</ul>
{% else %}
<p>Нет доступных жанров.</p>
{% endif %}



{% endblock %}